#!/usr/bin/env bash
# Build snocheck2 -- the verified prefix-rooted certificate checker.
#
# snocheck2 is a NEW binary. The frozen snocheck is never touched, never
# rebuilt, and remains the anchor for full-problem v1 certificates.
#
# WHAT LIVES WHERE, AND WHY
#   Only files that this campaign wrote are kept in this directory:
#       Prefix_Checker.thy         the verified extension (new)
#       Prefix_Checker_Codegen.thy the extraction setup (new)
#       ROOT                       the Isabelle session (new)
#       snocheck2/Decode2.hs       v1/v2/v2p container reader (new)
#       snocheck2/Translate2.hs    ProofStep -> verified datatypes (new)
#       snocheck2/Main.hs          CLI (new)
#   Three unchanged upstream modules (VectSet, ProofStep, Parallel) and the
#   five upstream theories are COPIED OUT OF THE PINNED CLONE at build time
#   rather than vendored here, so this directory contains no third-party code
#   and the pinned clone stays the single source of truth for it.
#   Verified/PrefixChecker.hs is generated by Isabelle, never committed.
#
# PREREQUISITES
#   ISABELLE  path to an Isabelle2020 (or 2019) `isabelle` executable.
#             Upstream README requires 2019 or 2020. The macOS bundle ships
#             prebuilt Pure and HOL heaps, so no HOL bootstrap is needed;
#             the whole session builds in well under a minute.
#   The GHC 8.6.5 and package db that the b3 toolchain already installed.
#
# USAGE
#   ISABELLE=/path/to/isabelle tools/verified/build.sh
#   Output: .build/v3-vcheck/snocheck2/snocheck2

set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SELF_DIR/../.." && pwd)"

CLONE="$ROOT_DIR/.cache/third_party/sortnetopt/checker"
WORK="$ROOT_DIR/.build/v3-vcheck"
GHC="${GHC:-$ROOT_DIR/.cache/toolchains/b3-stack-root/programs/x86_64-osx/ghc-8.6.5/bin/ghc}"
PKGDB="${PKGDB:-$ROOT_DIR/.cache/toolchains/b3-stack-root/snapshots/x86_64-osx/d1473faf13de27f8d4e264b417c0f8b159fc0e9036608c59c63fb7405449f749/8.6.5/pkgdb}"
ISABELLE="${ISABELLE:-isabelle}"

[ -d "$CLONE" ] || { echo "build.sh: pinned clone not found at $CLONE" >&2; exit 1; }

# ---- 1. baseline session: byte-identical copies of the upstream theories ----
# Only the ROOT differs: upstream asks for a PDF document, which needs a LaTeX
# toolchain we do not require here.
mkdir -p "$WORK/baseline"
cp "$CLONE"/verified/*.thy "$WORK/baseline/"
cat > "$WORK/baseline/ROOT" <<'EOF'
session Sorting_Networks = HOL +
  options [document = false]
  sessions
    "HOL-Library"
  theories
    Sorting_Network_Bound
    Huffman
    Sorting_Network
    Checker
    Checker_Codegen
  export_files
    "Sorting_Networks.Checker_Codegen:**"
EOF

# ---- 2. extension session ----
mkdir -p "$WORK/ext"
cp "$SELF_DIR/Prefix_Checker.thy" "$SELF_DIR/Prefix_Checker_Codegen.thy" "$SELF_DIR/ROOT" "$WORK/ext/"

echo "build.sh: building and extracting the verified checker (this also"
echo "          re-verifies every upstream proof)..."
( cd "$WORK/ext" && "$ISABELLE" build -d ../baseline -d . -e Sorting_Networks_Prefix )

# ---- 3. fidelity check: the regenerated upstream core must match the frozen one ----
# The only permitted differences are the header comment line and the three
# hunks of checker/verified/strict_and_parallel.patch.
GEN_BASE="$WORK/baseline/export/Sorting_Networks.Checker_Codegen/code/checker/Verified/Checker.hs"
if [ -f "$GEN_BASE" ]; then
  if diff "$GEN_BASE" "$CLONE/snocheck/src/Verified/Checker.hs" \
      | grep -qv '^[0-9,acd]*$\|^[<>-]' ; then :; fi
  echo "build.sh: regenerated upstream core differs from the frozen copy by:"
  diff "$GEN_BASE" "$CLONE/snocheck/src/Verified/Checker.hs" || true
  echo "build.sh: (expected: the header comment plus the three strict_and_parallel.patch hunks)"
fi

# ---- 4. assemble the Haskell tree ----
SRC="$WORK/snocheck2/src"
mkdir -p "$SRC/Verified"
# unchanged upstream modules, copied from the pinned clone (never vendored)
cp "$CLONE"/snocheck/src/VectSet.hs "$CLONE"/snocheck/src/ProofStep.hs \
   "$CLONE"/snocheck/src/Parallel.hs "$SRC/"
# this campaign's glue
cp "$SELF_DIR"/snocheck2/Decode2.hs "$SELF_DIR"/snocheck2/Translate2.hs \
   "$SELF_DIR"/snocheck2/Main.hs "$SRC/"
# the freshly extracted verified core
cp "$WORK/ext/export/Sorting_Networks_Prefix.Prefix_Checker_Codegen/code/prefixchecker/Verified/PrefixChecker.hs" \
   "$SRC/Verified/"

# the same three performance/parallelism edits the frozen build applies to its
# own extracted module (checker/verified/strict_and_parallel.patch)
python3 - "$SRC/Verified/PrefixChecker.hs" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read()
subs = [
    ("import qualified Prelude;\n",
     "import qualified Prelude;\nimport qualified Parallel;\n"),
    ("data Vect_trie = VtEmpty | VtNode Bool Vect_trie Vect_trie;",
     "data Vect_trie = VtEmpty | VtNode !Bool !Vect_trie !Vect_trie;"),
    ("par a b = b;", "par = Parallel.par;"),
]
for old, new in subs:
    if new.strip() in s:
        continue
    if s.count(old) != 1:
        raise SystemExit("build.sh: strict_and_parallel edit did not apply uniquely: %r" % old[:40])
    s = s.replace(old, new, 1)
open(p, "w").write(s)
print("build.sh: applied the three strict_and_parallel edits to PrefixChecker.hs")
PY

# ---- 5. compile ----
( cd "$WORK/snocheck2" && "$GHC" -package-db "$PKGDB" -isrc -outputdir build \
    -O2 -threaded -rtsopts "-with-rtsopts=-N" -o snocheck2 src/Main.hs )

echo
echo "build.sh: built $WORK/snocheck2/snocheck2"
echo "  snocheck2 -v FILE   v1/v2 full-problem check"
echo "  snocheck2 -p FILE   v2p prefix-rooted check"
echo
echo "Cross-validate with:  python3 $SELF_DIR/crosscheck.py $WORK/snocheck2/snocheck2 <v2p files...>"
